# Generated by Django 5.1.7 on 2025-05-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工具名称')),
                ('description', models.TextField(blank=True, verbose_name='工具描述')),
                ('icon', models.CharField(blank=True, default='fas fa-tools', max_length=100, verbose_name='图标类名')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='标签（逗号分隔）')),
                ('status', models.CharField(choices=[('beta', 'Beta'), ('stable', 'Stable')], default='stable', max_length=20, verbose_name='状态')),
                ('url', models.URLField(blank=True, verbose_name='工具链接')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
